export const GalleryData = [
  {
    id:1,
    title:'Library',
    image:'../../../../../src/assets/libraryImage/library1.png',
  },
  {
    id:2,
    title:'Library',
    image:'../../../../../src/assets/libraryImage/library2.png',
  },
  {
    id:3,
    title:'Library',
    image:'../../../../../src/assets/libraryImage/library3.jpg',
  },
  {
    id:4,
    title:'Library',
    image:'../../../../../src/assets/libraryImage/library4.jpg',
  },
  {
    id:5,
    title:'ComputerClub',
    image:'../../../../../src/assets/computerClub/computerclub1.png',
  },
  {
    id:6,
    title:'ComputerClub',
    image:'../../../../../src/assets/computerClub/computerclub2.png',
  },
  {
    id:7,
    title:'ComputerClub',
    image:'../../../../../src/assets/computerClub/computerclub3.jpg',
  },
  {
    id:8,
    title:'ComputerClub',
    image:'../../../../../src/assets/computerClub/computerclub5.jpg',
  },
  {
    id:9,
    title:'CulturalFunction',
    image:'../../../../../public/galleryimg/gi1.jpg',
  },
  {
    id:10,
    title:'CulturalFunction',
    image:'../../../../../public/galleryimg/gi2.jpg',
  },
  {
    id:11,
    title:'CulturalFunction',
    image:'../../../../../public/galleryimg/gi3.jpg',
  },
  {
    id:12,
    title:'CulturalFunction',
    image:'../../../../../public/galleryimg/gi4.jpg',
  },


];

